"use strict";

/**
 * One-shot importer for the `members` table.
 *
 * Run from the `backend` folder:
 *
 *     node scripts/import-members.js          # imports/updates rows
 *     node scripts/import-members.js --reset  # DROP + recreate the table first (destructive!)
 *
 * Connection settings are taken from the same `app/config/db.config.js`
 * the running API uses, so whatever DATABASE_URL / DB_NAME / DB_USER /
 * DB_PASSWORD you have configured for the backend is what gets written to.
 *
 * The script is idempotent: rerunning it just upserts the three rows by id.
 */

require("dotenv").config();

const { createSequelize } = require("../app/config/db.config");

const RESET = process.argv.includes("--reset");

const sequelize = createSequelize();

const DDL = `
CREATE TABLE IF NOT EXISTS members (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                varchar(100) NOT NULL,
    "position"          varchar(100),
    company             varchar(150),
    industry            varchar(100),
    bio                 text,
    email               varchar(100),
    phone               varchar(50),
    website             varchar(255),
    linkedin            varchar(255),
    facebook            varchar(255),
    photo               varchar(255),
    featured            smallint     DEFAULT 0,
    status              varchar(32)  DEFAULT 'active'
                                     CHECK (status IN ('active', 'inactive')),
    created_at          timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    membership_category varchar(100),
    join_date           date,
    membership_end_date date,
    transaction_date    date,
    payment_amount      varchar(50),
    transaction_id      varchar(100),
    is_active           smallint     DEFAULT 1,
    notes               text,
    instagram           varchar(255),
    whatsapp            varchar(255),
    wechat              varchar(255),
    kakaotalk           varchar(255),
    viber               varchar(255)
);

CREATE INDEX IF NOT EXISTS members_status_idx ON members (status);

CREATE OR REPLACE FUNCTION members_set_updated_at()
RETURNS trigger AS $func$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_members_set_updated_at ON members;
CREATE TRIGGER trg_members_set_updated_at
BEFORE UPDATE ON members
FOR EACH ROW EXECUTE FUNCTION members_set_updated_at();
`;

const ROWS = [
  {
    id: 2,
    name: "IDERSAIKHAN (IDEREE) Jargalsaikhan",
    position: "IDERSAIKHAN JARGALSAIKHAN",
    company: "TERGUUN GEREGE LLC - WWW.TSAAS.MN",
    industry: "SYNERGY",
    bio: "",
    email: "idersaikhan.ja@gmail.com",
    phone: "90091225",
    website: "",
    linkedin: "",
    facebook: "",
    photo: "69e5a66aea095_Idersaikhan.jpg",
    featured: 1,
    status: "active",
    created_at: "2026-03-14 15:31:15",
    updated_at: "2026-04-20 04:07:06",
    membership_category: "Office supplies / Paper production",
    join_date: null,
    membership_end_date: null,
    transaction_date: null,
    payment_amount: null,
    transaction_id: null,
    is_active: 1,
    notes: null,
    instagram: null,
    whatsapp: null,
    wechat: null,
    kakaotalk: null,
    viber: null,
  },
  {
    id: 4,
    name: "Эрдэнэ-Очирын Дэлгэрмаа",
    position: "Delgermaa Erdene-Ochir",
    company: "Тунамал Итгэл ХХК",
    industry: "SYNERGY",
    bio: "Манай компани нь БНХАУ-ын Хөх хотын Олон улсын худалдааны төвийн 2 давхарт өөрийн нэрийн дэлгүүртэй бөгөөд тус дэлгүүрт Монгол улсаас үндэсний онцлогтой бараа бүтээгдэхүүнийг борлуулж байна. Монгол улсаас бараа бүтээгдэхүүнээ манай дэлгүүрт ханган нийлүүлэх хүсэлтэй хувь хүн, компанитай хамтран ажиллана.",
    email: "aamregled@gmail.com",
    phone: "95095658",
    website: "",
    linkedin: "",
    facebook: "https://www.facebook.com/delgermaa.erka",
    photo: "https://res.cloudinary.com/dmuecwv6k/image/upload/v1777530681/bni/members/img_20260430_063119_db54bc3b.jpg",
    featured: 1,
    status: "active",
    created_at: "2026-03-14 15:31:15",
    updated_at: "2026-04-30 06:31:23",
    membership_category: "Хятад улсын импорт экспортын худалдаа",
    join_date: null,
    membership_end_date: "2030-03-06",
    transaction_date: null,
    payment_amount: null,
    transaction_id: "E2821421",
    is_active: 1,
    notes: null,
    instagram: "https://www.instagram.com/terbumtanbolohuu/",
    whatsapp: "https://+97695095648",
    wechat: "https://debeterbumtan",
    kakaotalk: "",
    viber: "https://+97695095658",
  },
  {
    id: 51,
    name: "Global Korea Agency",
    position: "Захирал",
    company: "Global Korea agency",
    industry: "Сургалт",
    bio: "Манай компани нь 2023 онд анх солонгос улс руу оюутан зуучлал, болон эрүүл мэндийн аялал зуучлалалын чиглэлээр үүсгэн үүсгэн байгуулагдсан бөгөөд өдгөө үйл ажиллагаа өргөжүүлж олон улсын гадаад болон дотоод аялал жуучлал, визний материал бүрдүүлэлт, Солонгос улсын эрүүл мэндийн чиглэлээр онлайн виз мэдүүлэгийн албан ёсны төлөөлөгч, байгууллага юм.",
    email: "haenbugc@gmail.com",
    phone: "",
    website: "",
    linkedin: "",
    facebook: "https://www.facebook.com/share/18TWcUJmBr/?mibextid=wwXIfr",
    photo: "pf_69f47624f07c73.98093061.jpg",
    featured: 1,
    status: "active",
    created_at: "2026-04-30 08:08:50",
    updated_at: "2026-05-01 09:45:08",
    membership_category: null,
    join_date: null,
    membership_end_date: null,
    transaction_date: null,
    payment_amount: null,
    transaction_id: null,
    is_active: 1,
    notes: null,
    instagram: "",
    whatsapp: "",
    wechat: "",
    kakaotalk: "",
    viber: "https://vb.me/letsChatOnViber",
  },
];

const COLUMNS = [
  "id", "name", "position", "company", "industry", "bio", "email", "phone",
  "website", "linkedin", "facebook", "photo", "featured", "status",
  "created_at", "updated_at", "membership_category", "join_date",
  "membership_end_date", "transaction_date", "payment_amount",
  "transaction_id", "is_active", "notes", "instagram", "whatsapp",
  "wechat", "kakaotalk", "viber",
];

const UPSERT_SQL = `
INSERT INTO members (${COLUMNS.map((c) => `"${c}"`).join(", ")})
VALUES (${COLUMNS.map((_, i) => `$${i + 1}`).join(", ")})
ON CONFLICT (id) DO UPDATE SET
  ${COLUMNS.filter((c) => c !== "id").map((c) => `"${c}" = EXCLUDED."${c}"`).join(",\n  ")}
RETURNING id;
`;

async function main() {
  const cfg = sequelize.config || {};
  console.log(
    `→ Connecting to postgres://${cfg.username || "?"}@${cfg.host || "?"}:${cfg.port || "?"}/${cfg.database || "?"}`,
  );

  await sequelize.authenticate();
  console.log("✓ Connected.");

  if (RESET) {
    console.log("⚠ --reset passed: dropping `members` table");
    await sequelize.query("DROP TABLE IF EXISTS members CASCADE;");
  }

  console.log("→ Ensuring schema (CREATE TABLE IF NOT EXISTS, trigger, index)");
  await sequelize.query(DDL);

  console.log(`→ Upserting ${ROWS.length} member rows`);
  let inserted = 0;
  for (const row of ROWS) {
    const values = COLUMNS.map((c) => row[c] ?? null);
    const [, meta] = await sequelize.query(UPSERT_SQL, {
      bind: values,
    });
    inserted += meta?.rowCount ?? 0;
  }
  console.log(`✓ Upserted (${inserted} row writes).`);

  await sequelize.query(`
    SELECT setval(
      pg_get_serial_sequence('members', 'id'),
      GREATEST((SELECT COALESCE(MAX(id), 0) FROM members), 51)
    );
  `);
  console.log("✓ Bumped `id` identity sequence past max(id).");

  const [rows] = await sequelize.query(
    "SELECT id, name, company, industry, featured, status FROM members ORDER BY id;",
  );
  console.log("\nCurrent rows in `members`:");
  for (const r of rows) {
    console.log(
      `  #${r.id}  ${r.featured ? "★" : " "}  ${r.status}  ${r.company || r.name}  (${r.industry || "—"})`,
    );
  }
}

main()
  .then(() => sequelize.close())
  .then(() => process.exit(0))
  .catch(async (err) => {
    console.error("\n✗ Import failed:", err.message);
    if (err.original) console.error("  pg detail:", err.original.message);
    try { await sequelize.close(); } catch {}
    process.exit(1);
  });
