-- =====================================================================
-- bni_platform_profiles  (PostgreSQL)
-- ---------------------------------------------------------------------
-- Converted from the MySQL dump of `altansud_new`.`bni_platform_profiles`.
--
-- Differences vs. MySQL:
--   * `bigint UNSIGNED`     → `bigint`        (Postgres has no unsigned int)
--   * `mediumtext`          → `text`
--   * `longtext` JSON blob  → `jsonb`         (so we can query/index it)
--   * `datetime`            → `timestamptz`
--   * `ON UPDATE CURRENT_TIMESTAMP` → `BEFORE UPDATE` trigger (Postgres has
--     no row-level ON UPDATE clause).
--   * Long string values use dollar-quoting `$xx$ … $xx$` so we don't have
--     to escape `'`, `"`, `\` or newlines inside JSON / Mongolian text.
--
-- Safe to run repeatedly: every CREATE uses IF NOT EXISTS, every INSERT
-- uses ON CONFLICT DO UPDATE.
--
-- HOW TO USE in pgAdmin
--   1. Right-click the **database** node (NOT a table) → Query Tool.
--      (Right-clicking a table that this script later drops/creates is
--       what produces the "specified object could not be found" error.)
--   2. Paste the whole file → ▶ Execute.
--   3. Verify:  SELECT account_id, display_name, company_name
--               FROM bni_platform_profiles ORDER BY account_id;
-- =====================================================================

BEGIN;

-- ---------- 1. Sequelize-compatible enums (idempotent) ---------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_bni_platform_accounts_role') THEN
        CREATE TYPE enum_bni_platform_accounts_role
            AS ENUM ('visitor', 'member', 'director', 'admin');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_bni_platform_accounts_status') THEN
        CREATE TYPE enum_bni_platform_accounts_status
            AS ENUM ('active', 'suspended', 'deleted');
    END IF;
END
$$;

-- ---------- 2. bni_platform_accounts (parent of the FK) --------------
CREATE TABLE IF NOT EXISTS bni_platform_accounts (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                       varchar(255) NOT NULL UNIQUE,
    password_hash               varchar(255),
    password_reset_token_hash   char(64),
    password_reset_expires_at   timestamptz,
    google_sub                  varchar(64) UNIQUE,
    role                        enum_bni_platform_accounts_role   NOT NULL DEFAULT 'visitor',
    status                      enum_bni_platform_accounts_status NOT NULL DEFAULT 'active',
    email_verified_at           timestamptz,
    last_login_at               timestamptz,
    created_at                  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------- 3. bni_platform_profiles ---------------------------------
CREATE TABLE IF NOT EXISTS bni_platform_profiles (
    account_id           bigint      PRIMARY KEY
                                     REFERENCES bni_platform_accounts(id)
                                     ON DELETE CASCADE,
    display_name         varchar(255) NOT NULL DEFAULT '',
    bio                  text,
    photo_url            text,
    company_name         varchar(255),
    business_phone       varchar(64),
    business_email       varchar(255),
    website              varchar(512),
    address_line         varchar(512),
    business_json        jsonb,
    updated_at           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unique_profile_until timestamptz,
    unique_badge_url     varchar(512)
);

-- ---------- 4. updated_at auto-touch trigger -------------------------
CREATE OR REPLACE FUNCTION bni_platform_profiles_set_updated_at()
RETURNS trigger AS $func$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_bni_platform_profiles_set_updated_at ON bni_platform_profiles;
CREATE TRIGGER trg_bni_platform_profiles_set_updated_at
BEFORE UPDATE ON bni_platform_profiles
FOR EACH ROW EXECUTE FUNCTION bni_platform_profiles_set_updated_at();

-- ---------- 5. Seed minimal accounts so the FK resolves --------------
-- Account #1 is the "system / BNI" author the legacy `news.author_id = 1`
-- rows point at. The rest match your profile dump (ids 2–9).
INSERT INTO bni_platform_accounts (id, email, role, status, created_at, updated_at) VALUES
    (1, 'system@bni.local',  'admin',  'active', '2026-03-14 04:21:20+00', '2026-03-14 04:21:20+00'),
    (2, 'bayakaa@bni.local', 'member', 'active', '2026-04-13 14:36:33+00', '2026-05-01 11:58:21+00'),
    (3, 'idersaikhan@bni.local', 'member', 'active', '2026-04-13 14:36:33+00', '2026-04-13 14:36:33+00'),
    (4, 'khereed@bni.local', 'member', 'active', '2026-04-24 14:59:40+00', '2026-05-01 12:48:51+00'),
    (5, 'jargal@bni.local',  'member', 'active', '2026-04-24 14:59:40+00', '2026-05-01 12:59:09+00'),
    (6, 'bbbb@bni.local',    'visitor','active', '2026-04-24 14:59:40+00', '2026-04-24 14:59:40+00'),
    (7, 'delgermaa@bni.local','member','active', '2026-04-29 07:29:29+00', '2026-04-29 07:29:29+00'),
    (8, 'uranchimeg@bni.local','member','active','2026-05-01 08:43:13+00', '2026-05-01 08:43:13+00'),
    (9, 'gka@bni.local',     'member', 'active', '2026-05-01 09:45:00+00', '2026-05-01 09:45:00+00')
ON CONFLICT (id) DO NOTHING;

-- Bump the identity sequence past the seeded ids
SELECT setval(
    pg_get_serial_sequence('bni_platform_accounts', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 0) FROM bni_platform_accounts), 9)
);

-- ---------- 6. Profile rows ------------------------------------------
-- account 1 — system byline used by all legacy `news.author_id = 1` rows
INSERT INTO bni_platform_profiles (
    account_id, display_name, bio, photo_url, company_name,
    business_phone, business_email, website, address_line,
    business_json, updated_at
) VALUES (
    1,
    'BNI Систем',
    'Системээс автоматаар нийтэлсэн мэдээ.',
    NULL,
    'BNI Mongolia',
    NULL, 'system@bni.local', 'https://busy.mn', NULL,
    NULL,
    '2026-03-14 04:21:20+00'
)
ON CONFLICT (account_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    bio          = EXCLUDED.bio,
    photo_url    = EXCLUDED.photo_url,
    company_name = EXCLUDED.company_name,
    business_phone = EXCLUDED.business_phone,
    business_email = EXCLUDED.business_email,
    website        = EXCLUDED.website,
    address_line   = EXCLUDED.address_line,
    business_json  = EXCLUDED.business_json;

-- account 2 — Bayakaa Lkhamaa  (Terguun gerege)
-- NOTE: original row had two base64 PNG `hero_slides` (~100 KB).  They are
-- preserved verbatim inside the dollar-quoted block below — copy/paste safe.
INSERT INTO bni_platform_profiles (
    account_id, display_name, bio, photo_url, company_name,
    business_phone, business_email, website, address_line,
    business_json, updated_at
) VALUES (
    2,
    'Bayakaa Lkhamaa',
    '',
    'https://lh3.googleusercontent.com/a/ACg8ocIv1BFKFZEVECwtPRwmeZkmkWnu5LG28OsHvCggsq0lxDtqWA=s96-c',
    'Terguun gerege',
    '70005060', 'info@gerege.mn', 'https://tsaas.mn', '19 horoolol',
    $json$
{"industry":"SYNERGY","company_size":"20","founded_year":"2015","slogan":"","hero_slides":[],"profession_activity":"","company_location":"","years_in_business":"","previous_work":"","member_photo_url":"https:\/\/res.cloudinary.com\/dmuecwv6k\/image\/upload\/v1777344876\/bni\/company\/img_20260428_025434_073ecb0f.png","facebook":"https:\/\/facebook.com\/baykaa.kira","instagram":"https:\/\/instagram.com\/baykaa_g","whatsapp":"","wechat":"","kakaotalk":"","viber":"https:\/\/88064537"}
    $json$::jsonb,
    '2026-05-01 11:58:21+00'
)
ON CONFLICT (account_id) DO UPDATE SET
    display_name   = EXCLUDED.display_name,
    bio            = EXCLUDED.bio,
    photo_url      = EXCLUDED.photo_url,
    company_name   = EXCLUDED.company_name,
    business_phone = EXCLUDED.business_phone,
    business_email = EXCLUDED.business_email,
    website        = EXCLUDED.website,
    address_line   = EXCLUDED.address_line,
    business_json  = EXCLUDED.business_json;

-- account 3 — Idersaikhan Jargalsaikhan
INSERT INTO bni_platform_profiles (
    account_id, display_name, bio, photo_url, company_name,
    business_phone, business_email, website, address_line,
    business_json, updated_at
) VALUES (
    3,
    'Idersaikhan Jargalsaikhan',
    NULL,
    'https://lh3.googleusercontent.com/a/ACg8ocLLBLB0tKeZr0LOISew-wTgGca8H0DeKQWVug03Vz2rePq1A2K7=s96-c',
    NULL, NULL, NULL, NULL, NULL, NULL,
    '2026-04-13 14:36:33+00'
)
ON CONFLICT (account_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    photo_url    = EXCLUDED.photo_url;

-- account 4 — khereed khereed (Zenith Digital)
INSERT INTO bni_platform_profiles (
    account_id, display_name, bio, photo_url, company_name,
    business_phone, business_email, website, address_line,
    business_json, updated_at
) VALUES (
    4,
    'khereed khereed',
    'Маш өндөр бүтээмжтэй компани',
    'https://res.cloudinary.com/dmuecwv6k/image/upload/v1777637720/bni/company/img_20260501_121510_6bd9ceb0.png',
    'Zenith Digital',
    '99999999', 'info@khereed.mn', '', '',
    $json$
{"industry":"Худалдаа","company_size":"Жижиг","founded_year":"2020","slogan":"","profession_activity":"","company_location":"Улаанбаатар хот, Дунд голын зам","years_in_business":"","previous_work":"","facebook":"","instagram":"","whatsapp":"","wechat":"","kakaotalk":"","viber":"","address_country":"","address_city":"","address_district":"","address_postal":"","register_number":"","bank_code":"mbank","bank_name":"М банк","bank_account_number":"","profile_cover_url":"https:\/\/res.cloudinary.com\/dmuecwv6k\/image\/upload\/v1777638500\/bni\/company\/img_20260501_122816_ae884a30.png","member_photo_url":"https:\/\/res.cloudinary.com\/dmuecwv6k\/image\/upload\/v1777639731\/bni\/company\/img_20260501_124846_713bc623.png"}
    $json$::jsonb,
    '2026-05-01 12:48:51+00'
)
ON CONFLICT (account_id) DO UPDATE SET
    display_name   = EXCLUDED.display_name,
    bio            = EXCLUDED.bio,
    photo_url      = EXCLUDED.photo_url,
    company_name   = EXCLUDED.company_name,
    business_phone = EXCLUDED.business_phone,
    business_email = EXCLUDED.business_email,
    website        = EXCLUDED.website,
    address_line   = EXCLUDED.address_line,
    business_json  = EXCLUDED.business_json;

-- account 5 — Jargalsaikhan Idersaikhan (Тэргүүн Гэрэгэ ХХК)
INSERT INTO bni_platform_profiles (
    account_id, display_name, bio, photo_url, company_name,
    business_phone, business_email, website, address_line,
    business_json, updated_at
) VALUES (
    5,
    'Jargalsaikhan Idersaikhan',
    $bio$ТЭРГҮҮН ГЭРЭГЭ ХХК
Компанийн танилцуулга

Тэргүүн Гэрэгэ ХХК нь мэдээллийн технологи, POS болон хэвлэлийн цаасны үйлдвэрлэл, нийлүүлэлтийн чиглэлээр тогтвортой үйл ажиллагаа явуулж буй үндэсний компани юм. Манай компани нь Монгол Улсын зах зээлд олон жилийн турш чанартай бүтээгдэхүүн, найдвартай үйлчилгээ нийлүүлж, харилцагч байгууллагуудынхаа үйл ажиллагаанд бодит үнэ цэнэ бий болгох зорилготой ажиллаж ирсэн.

Бид бизнесийн байгууллага, худалдаа үйлчилгээний салбар, төрийн болон хувийн хэвшлийн хэрэглэгчдэд зориулсан POS цаас, кассын болон баримтын цаас, албан хэрэгцээний цаас, түүнчлэн мэдээллийн технологийн шийдэл, худалдаа түгээлтийн дэмжих системүүдийг нийлүүлэн ажиллаж байна.

Сүүлийн жилүүдэд манай компани үйлдвэрлэлийн хүчин чадлаа нэмэгдүүлж, дотоодын зах зээлийн хэрэгцээнд нийцсэн A4, A3 бичгийн цаасны үйлдвэрлэлийн шинэ шугам нэвтрүүлэн хөгжлийн дараагийн шатандаа шилжээд байна. Мөн байгаль орчинд ээлтэй бүтээгдэхүүн хөгжүүлэх чиглэлээр ажиллаж, эко POS цаасны патенттай үндэсний үйлдвэрлэгчийн хувьд зах зээлд өрсөлдөхүйц давуу талыг бүрдүүлсэн.

Бидний зорилго
Монгол Улсад чанартай, найдвартай, хүртээмжтэй цаасны үйлдвэрлэл, нийлүүлэлтийн тогтолцоог хөгжүүлж, хэрэглэгчдэд олон улсын жишигт нийцсэн бүтээгдэхүүн үйлчилгээг хүргэхэд оршино.$bio$,
    'https://lh3.googleusercontent.com/a/ACg8ocLYz32PT2LOMW-arSgdEDYVZEE4j2BSi2VLOdADKraRUmfxAUkg=s96-c',
    'Тэргүүн Гэрэгэ ХХК',
    '70005060', 'terguungerege@gmail.com', 'http://tsaas.mn/',
    'Ulaanbaatar,KHUD,2nd khoroo, Dund Gol street, Build 34-2',
    $json$
{"industry":"Мэдээллийн технологи, Жижиг дунд үйлдвэрлэл","company_size":"Том","founded_year":"2015","slogan":"Цаасан дээр бичсэн хүсэл бүхэн биелэдэг","hero_slides":["https:\/\/res.cloudinary.com\/dmuecwv6k\/image\/upload\/v1776861369\/bni\/company\/img_20260422_123606_c786daf2.jpg","https:\/\/res.cloudinary.com\/dmuecwv6k\/image\/upload\/v1777531020\/bni\/company\/img_20260430_063658_ecef66cd.jpg"],"profession_activity":"","company_location":"","years_in_business":"","previous_work":"","facebook":"","instagram":"","whatsapp":"","wechat":"","kakaotalk":"","viber":"","member_photo_url":"https:\/\/res.cloudinary.com\/dmuecwv6k\/image\/upload\/v1777566449\/bni\/company\/img_20260430_162712_fed6d049.png"}
    $json$::jsonb,
    '2026-05-01 12:59:09+00'
)
ON CONFLICT (account_id) DO UPDATE SET
    display_name   = EXCLUDED.display_name,
    bio            = EXCLUDED.bio,
    photo_url      = EXCLUDED.photo_url,
    company_name   = EXCLUDED.company_name,
    business_phone = EXCLUDED.business_phone,
    business_email = EXCLUDED.business_email,
    website        = EXCLUDED.website,
    address_line   = EXCLUDED.address_line,
    business_json  = EXCLUDED.business_json;

-- account 6 — bbbb (placeholder)
INSERT INTO bni_platform_profiles (
    account_id, display_name, updated_at
) VALUES (
    6, 'bbbb', '2026-04-24 14:59:40+00'
)
ON CONFLICT (account_id) DO UPDATE SET display_name = EXCLUDED.display_name;

-- account 7 — Эрдэнэ-Очирын Дэлгэрмаа (Тунамал Итгэл ХХК)
INSERT INTO bni_platform_profiles (
    account_id, display_name, bio, photo_url, company_name,
    business_phone, business_email, website, address_line,
    business_json, updated_at
) VALUES (
    7,
    'Эрдэнэ-Очирын Дэлгэрмаа',
    'Манай компани нь БНХАУ-ын Хөх хотын Олон улсын худалдааны төвийн 2 давхарт өөрийн нэрийн дэлгүүртэй бөгөөд тус дэлгүүрт Монгол улсаас үндэсний онцлогтой бараа бүтээгдэхүүнийг борлуулж байна. Монгол улсаас бараа бүтээгдэхүүнээ манай дэлгүүрт ханган нийлүүлэх хүсэлтэй хувь хүн, компанитай хамтран ажиллана.',
    'https://res.cloudinary.com/dmuecwv6k/image/upload/v1777447403/bni/company/img_20260429_072321_30d8f393.jpg',
    'Тунамал Итгэл ХХК',
    '95095658', 'aamregled@gmail.com', '',
    'Улаанбаатар хот , Сүхбаатар дүүрэг , 9-р хороо, Компьютер малл худ төв',
    $json$
{"industry":"гадаад худалдаа экспорт болон импорт","company_size":"10сая","founded_year":"2025","slogan":"Монголын экспорт мандтугай.","profession_activity":"Борлуулалт, төслийн менежер","company_location":"СБД, 9р хороо, Компьютер малл худалдааны төв","years_in_business":"20 жил","previous_work":"Төслийн менежер","member_photo_url":"https:\/\/res.cloudinary.com\/dmuecwv6k\/image\/upload\/v1777348724\/bni\/company\/img_20260428_035837_85c65e66.jpg","facebook":"https:\/\/www.facebook.com\/delgermaa.erka","instagram":"https:\/\/www.instagram.com\/terbumtanbolohuu\/","whatsapp":"https:\/\/+97695095648","wechat":"https:\/\/debeterbumtan","kakaotalk":"","viber":"https:\/\/+97695095658"}
    $json$::jsonb,
    '2026-04-29 07:29:29+00'
)
ON CONFLICT (account_id) DO UPDATE SET
    display_name   = EXCLUDED.display_name,
    bio            = EXCLUDED.bio,
    photo_url      = EXCLUDED.photo_url,
    company_name   = EXCLUDED.company_name,
    business_phone = EXCLUDED.business_phone,
    business_email = EXCLUDED.business_email,
    website        = EXCLUDED.website,
    address_line   = EXCLUDED.address_line,
    business_json  = EXCLUDED.business_json;

-- account 8 — Уранчимэг (GLOBAL KOREA AGENCY GROUP)
INSERT INTO bni_platform_profiles (
    account_id, display_name, bio, photo_url, company_name,
    business_phone, business_email, website, address_line,
    business_json, updated_at
) VALUES (
    8,
    'Мөнхөө овогтой Уранчимэг',
    'Манай компани БНСУ-ийн Бусан хотын эрүүл мэнд, боловсрол жуулчлалын монгол талын албан ёсны төлөөлөгч байгуулага бөгөөд өдгөө монгол улсаас БНСУ-н томоохон хотууд болох Сөүл, Инчон Тэгү хотуудын их дээд сургууль руу 30-100%-н тэтгэлэгтэй 589-гаад оюутан баклавр магистр, докторын ангиудад элсэн суралцаад байна.',
    'https://res.cloudinary.com/dmuecwv6k/image/upload/v1777624992/bni/company/img_20260501_084310_ff8c7457.jpg',
    'GLOBAL KOREA AGENCY GROUP',
    '88199713', 'gkagecyk@gmail.com', '',
    'M-Plaza - 8floor - 806',
    $json$
{"industry":"Үйлчилгээ","company_size":"Дунд","founded_year":"2024","slogan":"Таны аялал бидний хариуцлага","profession_activity":"Business Tour and EDU consulting","company_location":"ЧД 5-Р ХОРОО М ПЛАЗА 806 ТООТ","years_in_business":"5 ЖИЛ","previous_work":"Үйлдвэрлэл, үйлчилгээ, Солонгос улсын бүх чиглэлийн үйлчилгээ","facebook":"https:\/\/www.facebook.com\/share\/18TWcUJmBr\/","instagram":"","whatsapp":"","wechat":"","kakaotalk":"","viber":""}
    $json$::jsonb,
    '2026-05-01 08:43:13+00'
)
ON CONFLICT (account_id) DO UPDATE SET
    display_name   = EXCLUDED.display_name,
    bio            = EXCLUDED.bio,
    photo_url      = EXCLUDED.photo_url,
    company_name   = EXCLUDED.company_name,
    business_phone = EXCLUDED.business_phone,
    business_email = EXCLUDED.business_email,
    website        = EXCLUDED.website,
    address_line   = EXCLUDED.address_line,
    business_json  = EXCLUDED.business_json;

-- account 9 — Global Korea Agency
INSERT INTO bni_platform_profiles (
    account_id, display_name, bio, photo_url, company_name,
    business_phone, business_email, website, address_line,
    business_json, updated_at
) VALUES (
    9,
    'Global Korea Agency',
    'Манай компани нь 2023 онд анх солонгос улс руу оюутан зуучлал, болон эрүүл мэндийн аялал зуучлалалын чиглэлээр үүсгэн үүсгэн байгуулагдсан бөгөөд өдгөө үйл ажиллагаа өргөжүүлж олон улсын гадаад болон дотоод аялал жуучлал, визний материал бүрдүүлэлт, Солонгос улсын эрүүл мэндийн чиглэлээр онлайн виз мэдүүлэгийн албан ёсны төлөөлөгч, байгууллага юм.',
    'https://res.cloudinary.com/dmuecwv6k/image/upload/v1777628199/bni/company/img_20260501_093638_9a4ac592.jpg',
    'Global Korea agency',
    '', '', '', 'M-Plaza 8 floor 806',
    $json$
{"industry":"Үйлчилгээ","company_size":"Дунд","founded_year":"2024","slogan":"Итгэлээр холбож, Амжилтаар батална","profession_activity":"Visa consulting , EDU ,Tour service","company_location":"Улаанбаатар хот","years_in_business":"5+ жил","previous_work":"Үйлдвэрлэл, Үйлчилгээ, Солонгос улсын бүх чиглэлийн үйлчилгээ, зөвөлгөө","facebook":"https:\/\/www.facebook.com\/share\/18TWcUJmBr\/?mibextid=wwXIfr","instagram":"","whatsapp":"","wechat":"","kakaotalk":"","viber":"https:\/\/vb.me\/letsChatOnViber","member_photo_url":"https:\/\/res.cloudinary.com\/dmuecwv6k\/image\/upload\/v1777628197\/bni\/company\/img_20260501_093634_22896209.jpg"}
    $json$::jsonb,
    '2026-05-01 09:45:00+00'
)
ON CONFLICT (account_id) DO UPDATE SET
    display_name   = EXCLUDED.display_name,
    bio            = EXCLUDED.bio,
    photo_url      = EXCLUDED.photo_url,
    company_name   = EXCLUDED.company_name,
    business_phone = EXCLUDED.business_phone,
    business_email = EXCLUDED.business_email,
    website        = EXCLUDED.website,
    address_line   = EXCLUDED.address_line,
    business_json  = EXCLUDED.business_json;

COMMIT;

-- ---------- 7. Quick smoke check -------------------------------------
-- SELECT account_id, display_name, company_name, photo_url IS NOT NULL AS has_photo
-- FROM bni_platform_profiles ORDER BY account_id;
